[env:lilygo-sim7600e]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200

lib_deps =
    vshymanskyy/TinyGSM@^0.11.7
    arduino-libraries/ArduinoHttpClient@^0.6.1

build_flags =
    -DTINY_GSM_MODEM_SIM7600
    -DTINY_GSM_RX_BUFFER=1024
